services:
  - type: web
    name: acharfrancebot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: REMOVEBG_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false